package main

type HaproxyStats struct {
	ProxyName         string `csv:"pxname"`
	ServiceName       string `csv:"svname"`
	CurrQueuedReq     int    `csv:"qcur"`
	MaxQueuedReq      int    `csv:"qmax"`
	CurrSessions      int    `csv:"scur"`
	MaxSessions       int    `csv:"smax"`
	SessionLimits     int    `csv:"slim"`
	TotalSessions     int    `csv:"stot"`
	BytesIn           int    `csv:"bin"`
	BytesOut          int    `csv:"bout"`
	DeniedRequests    int    `csv:"dreq"`
	DeniedResponses   int    `csv:"dresp"`
	RequestErrors     int    `csv:"ereq"`
	ConnectionErrors  int    `csv:"econ"`
	ResponseErrors    int    `csv:"eresp"`
	Retries           int    `csv:"wretr"`
	Redispatches      int    `csv:"wredis"`
	Status            string `csv:"status"`
	Weight            int    `csv:"weight"`
	Active            int    `csv:"act"`
	Backup            int    `csv:"bck"`
	FailedChecks      int    `csv:"chkfail"`
	UpDownTransitions int    `csv:"chkdown"`
	LastStatusChange  int    `csv:"lastchg"`
	Downtime          int    `csv:"downtime"`
	QueueLimit        int    `csv:"qlimit"`
	ProcessId         int    `csv:"pid"`
	UniqueProxyId     int    `csv:"iid"`
	ServiceId         int    `csv:"sid"`
	Throttle          string `csv:"throttle"`
	TotalSelected     int    `csv:"lbtot"`
	Tracked           int    `csv:"tracked"`
	Type              int    `csv:"type"`
	Rate              int    `csv:"rate"`
	RateLimit         int    `csv:"rate_lim"`
	RateMax           int    `csv:"rate_max"`
	StatusCheck       string `csv:"check_status"`
	CheckCode         string `csv:"check_code"`
	CheckDuration     int    `csv:"check_duration"`
	Http100           int    `csv:"hrsp_1xx"`
	Http200           int    `csv:"hrsp_2xx"`
	Http300           int    `csv:"hrsp_3xx"`
	Http400           int    `csv:"hrsp_4xx"`
	Http500           int    `csv:"hrsp_5xx"`
	HttpOther         int    `csv:"hrsp_other"`
	FailedHealth      int    `csv:"hanafail"`
	RequestRate       int    `csv:"req_rate"`
	MaxRequestRate    int    `csv:"req_rate_max"`
	TotalRequest      int    `csv:"req_tot"`
	CliAbort          int    `csv:"cli_abrt"`
	ServerAbort       int    `csv:"srv_abrt"`
	CompIn            int    `csv:"comp_in"`
	CompOut           int    `csv:"comp_out"`
	CompByp           int    `csv:"comp_byp"`
	CompRsp           int    `csv:"comp_rsp"`
	LastSess          int    `csv:"lastsess"`
	LastChk           int    `csv:"last_chk"`
	LastAgt           int    `csv:"last_agt"`
	Qtime             int    `csv:"qtime"`
	Ctime             int    `csv:"ctime"`
	Rtime             int    `csv:"rtime"`
	Ttime             int    `csv:"ttime"`
}
